In [3]:
import pandas as pd

In [4]:
apple = pd.read_csv('archive/stocks/AAPL.csv')
facebook = pd.read_csv('archive/stocks/FB.csv')
google = pd.read_csv('archive/stocks/GOOGL.csv')
nvidia = pd.read_csv('archive/stocks/NVDA.csv')
tesla = pd.read_csv('archive/stocks/TSLA.csv')
twitter = pd.read_csv('archive/stocks/TWTR.csv')

In [5]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400
...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200

In [6]:
facebook

,Date,Open,High,Low,Close,Adj Close,Volume
0,2012-05-18,42.049999,45.000000,38.000000,38.230000,38.230000,573576400
1,2012-05-21,36.529999,36.660000,33.000000,34.029999,34.029999,168192700
2,2012-05-22,32.610001,33.590000,30.940001,31.000000,31.000000,101786600
3,2012-05-23,31.370001,32.500000,31.360001,32.000000,32.000000,73600000
4,2012-05-24,32.950001,33.209999,31.770000,33.029999,33.029999,50237200
...,...,...,...,...,...,...,...
1975,2020-03-26,158.250000,164.000000,157.020004,163.339996,163.339996,26556800
1976,2020-03-27,158.199997,160.089996,154.750000,156.789993,156.789993,24879900
1977,2020-03-30,159.179993,166.750000,158.059998,165.949997,165.949997,22515200
1978,2020-03-31,165.479996,170.929993,164.199997,166.800003,166.800003,23676300
1979,2020-04-01,161.619995,164.149994,158.039993,159.600006,159.600006,19491500

In [7]:
google

,Date,Open,High,Low,Close,Adj Close,Volume
0,2004-08-19,50.050049,52.082081,48.028027,50.220219,50.220219,44659000
1,2004-08-20,50.555557,54.594593,50.300301,54.209209,54.209209,22834300
2,2004-08-23,55.430431,56.796795,54.579578,54.754753,54.754753,18256100
3,2004-08-24,55.675674,55.855854,51.836838,52.487488,52.487488,15247300
4,2004-08-25,52.532532,54.054054,51.991993,53.053055,53.053055,9188600
...,...,...,...,...,...,...,...
3927,2020-03-26,1114.719971,1171.479980,1092.030029,1162.920044,1162.920044,3828100
3928,2020-03-27,1127.469971,1151.050049,1104.000000,1110.260010,1110.260010,3139700
3929,2020-03-30,1132.640015,1151.000000,1098.489990,1146.310059,1146.310059,2936800
3930,2020-03-31,1148.729980,1173.400024,1136.719971,1161.949951,1161.949951,3261400
3931,2020-04-01,1124.000000,1129.420044,1093.489990,1102.099976,1102.099976,2597100

In [8]:
nvidia

,Date,Open,High,Low,Close,Adj Close,Volume
0,1999-01-22,1.750000,1.953125,1.552083,1.640625,1.509998,67867200.0
1,1999-01-25,1.770833,1.833333,1.640625,1.812500,1.668188,12762000.0
2,1999-01-26,1.833333,1.869792,1.645833,1.671875,1.538759,8580000.0
3,1999-01-27,1.677083,1.718750,1.583333,1.666667,1.533965,6109200.0
4,1999-01-28,1.666667,1.677083,1.651042,1.661458,1.529172,5688000.0
...,...,...,...,...,...,...,...
5329,2020-03-26,253.940002,262.220001,250.000000,257.239990,257.239990,17402700.0
5330,2020-03-27,250.000000,263.119995,248.679993,252.729996,252.729996,15970700.0
5331,2020-03-30,255.360001,265.959991,253.589996,265.589996,265.589996,15056300.0
5332,2020-03-31,267.200012,275.399994,257.750000,263.600006,263.600006,23749000.0
5333,2020-04-01,255.649994,261.529999,241.279999,243.070007,243.070007,16386900.0

In [9]:
tesla

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900
...,...,...,...,...,...,...,...
2452,2020-03-26,547.390015,560.000000,512.250000,528.159973,528.159973,17380700
2453,2020-03-27,505.000000,525.799988,494.029999,514.359985,514.359985,14377400
2454,2020-03-30,510.260010,516.650024,491.230011,502.130005,502.130005,11998100
2455,2020-03-31,501.250000,542.960022,497.000000,524.000000,524.000000,17771500
2456,2020-04-01,504.000000,513.950012,475.100006,481.559998,481.559998,13304500

In [10]:
twitter

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-11-07,45.099998,50.090000,44.000000,44.900002,44.900002,117701600
1,2013-11-08,45.930000,46.939999,40.689999,41.650002,41.650002,27925300
2,2013-11-11,40.500000,43.000000,39.400002,42.900002,42.900002,16113900
3,2013-11-12,43.660000,43.779999,41.830002,41.900002,41.900002,6316700
4,2013-11-13,41.029999,42.869999,40.759998,42.599998,42.599998,8688300
...,...,...,...,...,...,...,...
1605,2020-03-26,26.150000,27.030001,25.629999,26.410000,26.410000,20435300
1606,2020-03-27,25.559999,25.830000,24.760000,25.290001,25.290001,22069300
1607,2020-03-30,25.250000,25.940001,24.600000,25.590000,25.590000,20720800
1608,2020-03-31,25.790001,26.330000,24.400000,24.559999,24.559999,24993400
1609,2020-04-01,23.700001,24.389999,23.049999,23.320000,23.320000,20015700

In [11]:
dfs = [apple, facebook, google, nvidia, tesla, twitter]

In [12]:
# Apply moving average
for df in dfs:
    df['MA50'] = df.Close.rolling(50).mean()
    df['MA200'] = df.Close.rolling(200).mean()

In [13]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume,MA50,MA200
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,NaN,NaN
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,NaN,NaN
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,NaN,NaN
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,NaN,NaN
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,294.6510,249.47610
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,293.3790,249.74385
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,292.1704,250.04715
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,290.8816,250.35490
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,289.3684,250.59000

In [14]:
for df in dfs:
    df['Previous Day close price'] = df.Close.shift(1)

In [15]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume,MA50,MA200,Previous Day close price
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,NaN,NaN,NaN
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,NaN,NaN,0.513393
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,NaN,NaN,0.486607
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,NaN,NaN,0.450893
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,NaN,NaN,0.462054
...,...,...,...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,294.6510,249.47610,245.520004
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,293.3790,249.74385,258.440002
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,292.1704,250.04715,247.740005
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,290.8816,250.35490,254.809998
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,289.3684,250.59000,254.289993

In [16]:
for df in dfs:
    df['Change in price'] = df['Close'] - df['Previous Day close price']

In [17]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume,MA50,MA200,Previous Day close price,Change in price
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,NaN,NaN,NaN,NaN
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,NaN,NaN,0.513393,-0.026786
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,NaN,NaN,0.486607,-0.035714
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,NaN,NaN,0.450893,0.011161
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,NaN,NaN,0.462054,0.013393
...,...,...,...,...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,294.6510,249.47610,245.520004,12.919998
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,293.3790,249.74385,258.440002,-10.699997
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,292.1704,250.04715,247.740005,7.069992
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,290.8816,250.35490,254.809998,-0.520004
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,289.3684,250.59000,254.289993,-13.379990

In [18]:
for df in dfs:
    df['Percent change in price'] = df.Close.pct_change()

C:\Users\Ishaan\AppData\Local\Temp\ipykernel_35864\4113611974.py:2: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df['Percent change in price'] = df.Close.pct_change()

In [19]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume,MA50,MA200,Previous Day close price,Change in price,Percent change in price
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,NaN,NaN,NaN,NaN,NaN
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,NaN,NaN,0.513393,-0.026786,-0.052174
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,NaN,NaN,0.486607,-0.035714,-0.073394
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,NaN,NaN,0.450893,0.011161,0.024752
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,NaN,NaN,0.462054,0.013393,0.028986
...,...,...,...,...,...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,294.6510,249.47610,245.520004,12.919998,0.052623
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,293.3790,249.74385,258.440002,-10.699997,-0.041402
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,292.1704,250.04715,247.740005,7.069992,0.028538
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,290.8816,250.35490,254.809998,-0.520004,-0.002041
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,289.3684,250.59000,254.289993,-13.379990,-0.052617

In [20]:
for df in dfs:
    df['Previous day volume'] = df.Volume.shift(1)

In [21]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume,MA50,MA200,Previous Day close price,Change in price,Percent change in price,Previous day volume
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,NaN,NaN,NaN,NaN,NaN,NaN
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,NaN,NaN,0.513393,-0.026786,-0.052174,117258400.0
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,NaN,NaN,0.486607,-0.035714,-0.073394,43971200.0
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,NaN,NaN,0.450893,0.011161,0.024752,26432000.0
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,NaN,NaN,0.462054,0.013393,0.028986,21610400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,294.6510,249.47610,245.520004,12.919998,0.052623,75900500.0
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,293.3790,249.74385,258.440002,-10.699997,-0.041402,63021800.0
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,292.1704,250.04715,247.740005,7.069992,0.028538,51054200.0
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,290.8816,250.35490,254.809998,-0.520004,-0.002041,41994100.0
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,289.3684,250.59000,254.289993,-13.379990,-0.052617,49250500.0

In [22]:
for df in dfs:
    df['Change in volume'] = df['Volume'] - df['Previous day volume']

In [23]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume,MA50,MA200,Previous Day close price,Change in price,Percent change in price,Previous day volume,Change in volume
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,NaN,NaN,0.513393,-0.026786,-0.052174,117258400.0,-73287200.0
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,NaN,NaN,0.486607,-0.035714,-0.073394,43971200.0,-17539200.0
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,NaN,NaN,0.450893,0.011161,0.024752,26432000.0,-4821600.0
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,NaN,NaN,0.462054,0.013393,0.028986,21610400.0,-3248000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,294.6510,249.47610,245.520004,12.919998,0.052623,75900500.0,-12878700.0
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,293.3790,249.74385,258.440002,-10.699997,-0.041402,63021800.0,-11967600.0
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,292.1704,250.04715,247.740005,7.069992,0.028538,51054200.0,-9060100.0
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,290.8816,250.35490,254.809998,-0.520004,-0.002041,41994100.0,7256400.0
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,289.3684,250.59000,254.289993,-13.379990,-0.052617,49250500.0,-5294300.0

In [24]:
for df in dfs:
    df['Percent change in volume'] = df.Volume.pct_change()

C:\Users\Ishaan\AppData\Local\Temp\ipykernel_35864\3897017074.py:2: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df['Percent change in volume'] = df.Volume.pct_change()

In [25]:
apple

,Date,Open,High,Low,Close,Adj Close,Volume,MA50,MA200,Previous Day close price,Change in price,Percent change in price,Previous day volume,Change in volume,Percent change in volume
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200,NaN,NaN,0.513393,-0.026786,-0.052174,117258400.0,-73287200.0,-0.625006
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000,NaN,NaN,0.486607,-0.035714,-0.073394,43971200.0,-17539200.0,-0.398879
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400,NaN,NaN,0.450893,0.011161,0.024752,26432000.0,-4821600.0,-0.182415
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400,NaN,NaN,0.462054,0.013393,0.028986,21610400.0,-3248000.0,-0.150298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800,294.6510,249.47610,245.520004,12.919998,0.052623,75900500.0,-12878700.0,-0.169679
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200,293.3790,249.74385,258.440002,-10.699997,-0.041402,63021800.0,-11967600.0,-0.189896
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100,292.1704,250.04715,247.740005,7.069992,0.028538,51054200.0,-9060100.0,-0.177460
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500,290.8816,250.35490,254.809998,-0.520004,-0.002041,41994100.0,7256400.0,0.172796
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200,289.3684,250.59000,254.289993,-13.379990,-0.052617,49250500.0,-5294300.0,-0.107497

In [26]:
apple.to_csv('Apple.csv')
facebook.to_csv('Facebook.csv')
google.to_csv('Google.csv')
nvidia.to_csv('Nvidia.csv')
tesla.to_csv('Tesla.csv')
twitter.to_csv('Twitter.csv')